services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - .:/var/www/sitemap
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
      #- /etc/apache2/.htpasswd:/etc/apache2/.htpasswd # uncomment for dev mode
    depends_on:
      - php
      - mysql
    networks:
      - app-network
  php:
    container_name: php
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: php:latest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '9000:9000'
    volumes:
      - '.:/var/www/sitemap'
      - ./docker/php.ini:/usr/local/etc/php/php.ini:ro
    networks:
      - app-network
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '${APP_PORT:-3306}:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - .:/var/www/sitemap
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
